# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 04:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('number_seats', models.IntegerField()),
                ('booked_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('booked_classrooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_display.Classroom')),
            ],
        ),
    ]
