# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 02:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_display', '0002_auto_20160425_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='booked_date',
        ),
    ]
