# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room_display', '0003_remove_classroom_booked_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
        migrations.AddField(
            model_name='randomuser',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_display.Booking'),
        ),
    ]
