# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 03:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('room_display', '0005_auto_20160425_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_stop',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
