# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_display', '0008_auto_20160501_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.IntegerField(default=1),
        ),
    ]
