# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_display', '0010_booking_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='key',
            field=models.CharField(default='8fc011cfe950482caa5bf3a92b5d7af6', max_length=32),
        ),
    ]
