# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-01 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_display', '0011_auto_20170528_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='key',
            field=models.CharField(default='24a76f34b5d748acb60c8707c3a0f7df', max_length=32),
        ),
    ]
