# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-23 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_display', '0011_auto_20170528_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='key',
            field=models.CharField(default='ad2cdf08f08c4f54af436cc113030dcf', max_length=32),
        ),
    ]
