# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-16 23:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_display', '0012_auto_20170701_1520'),
        ('room_display', '0012_auto_20170701_1522'),
    ]

    operations = [
    ]
